Microsoft/winsdkfb

FBWinSDK/FBSDK-UWP/FBSDK-UWP/FBSDK-UWP.vcxproj
FBWinSDK/FBWinSDK/FBWinSDK.Shared/FacebookSession.cpp
FBWinSDK/FBWinSDK/FBWinSDK.Windows/FBWinSDK.Windows.vcxproj
FBWinSDK/FBWinSDK/FBWinSDK.WindowsPhone/FBWinSDK.WindowsPhone.vcxproj
FBWinSDK/build/build-sdk.cmd
samples/LoginCpp-UWP/LoginCpp-UWP.sln
samples/LoginCpp-UWP/LoginCpp/LoginCpp.vcxproj
samples/LoginCpp-UWP/LoginCpp/LoginCpp.vcxproj.filters
samples/LoginCpp-UWP/LoginCpp/packages.config
samples/LoginCpp/LoginCpp.sln
samples/LoginCpp/LoginCpp/LoginCpp.Windows/LoginCpp.Windows.vcxproj
samples/LoginCpp/LoginCpp/LoginCpp.Windows/LoginCpp.Windows.vcxproj.filters
samples/LoginCpp/LoginCpp/LoginCpp.Windows/packages.config
samples/LoginCpp/LoginCpp/LoginCpp.WindowsPhone/LoginCpp.WindowsPhone.vcxproj
samples/LoginCpp/LoginCpp/LoginCpp.WindowsPhone/LoginCpp.WindowsPhone.vcxproj.filters
samples/LoginCpp/LoginCpp/LoginCpp.WindowsPhone/packages.config
samples/LoginCs/LoginCs.sln
samples/LoginCs/LoginCs/LoginCs.Shared/App.xaml.cs
samples/LoginCs/LoginCs/LoginCs.Windows/LoginCs.Windows.csproj
samples/LoginCs/LoginCs/LoginCs.Windows/MainPage.xaml.cs
samples/LoginCs/LoginCs/LoginCs.Windows/packages.config
samples/LoginCs/LoginCs/LoginCs.WindowsPhone/LoginCs.WindowsPhone.csproj
samples/LoginCs/LoginCs/LoginCs.WindowsPhone/MainPage.xaml.cs
samples/LoginCs/LoginCs/LoginCs.WindowsPhone/Package.appxmanifest
samples/LoginCs/LoginCs/LoginCs.WindowsPhone/packages.config

Had to also make some code changes to LoginCs project, but mostly this is just changing the way the samples refer to the SDK.  Samples all run properly again with the new setup.

26 change sample sdk references

---

FBWinSDK/FBWinSDK/FBWinSDK.Shared/FacebookClient.cpp

API version specification no longer causes WBWinStoreCsTests to fail.

request_host removes ability to specify api version

---

FBWinSDK/FBWinSDK/FBWinSDK.Shared/FacebookLoginButton.cpp
FBWinSDK/FBWinSDK/FBWinSDK.Shared/FacebookSession.cpp
FBWinSDK/FBWinSDK/FBWinSDK.Shared/FacebookSession.h

Added ability to select the method of login. Use enum class SessionLoginBehavior. Modified for real UWP application - WebView is very slowly for async operation without block of UI, so WebAuthBroker is more useful.

Choose login method

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml.cpp

`CoreApplication::MainView->CoreWindow->SizeChanged -= sizeChangedEventRegistrationToken;` isn't invoked in `FacebookDialog::CloseDialogButton_OnClick`. So, when you resize your app window after the Facebook dialog was closed, an unhandled exception is thrown.
`dialogWebBrowser->Stop();` is called before every `UninitDialog();` call. Seems like it should be inside the `FacebookDialog::UninitDialog`.

Bugfix: If you change the app window size an exception could be thrown

---

samples/LoginCpp-UWP/LoginCpp/Dialogs.xaml.cpp
samples/LoginCpp/LoginCpp/LoginCpp.Windows/Dialogs.xaml.cpp
samples/LoginCpp/LoginCpp/LoginCpp.WindowsPhone/Dialogs.xaml.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml.h

Fix when using Facebook Menu to log out in a FeedDialog (the www.facebook.com/logout.php is called but the token wasn't deleted).

Fix when using Facebook Menu to log out in a FeedDialog #103 (Tip N°2)

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml

Simple fix for #130 by making the login dialog smaller so it is never occluded by status bar on phone.

Fixing #130 when close button is occluded by status bar

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml.h
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.h

Hi!
I noticed that functions `FBSession::Show*DialogAsync()` use polling loop while waiting for `FacebookDialog`. I decided to rewrite that part in a more async way using `IAsyncOperation` and `task_completion_event`. Now there is no need for `FacebookDialog::GetDialogResponse()` and the code looks cleaner.
I also moved `FacebookDialog` creation to the UI thread, because its components are required to be initialized in the UI thread anyway.

FacebookDialog improvement: polling -> async with task_completion_event

---

_config.yml

Deleting the "markdown" option in the _config.yml file (as specified by GitHub pages support) breaks some of the markdown heading rendering in the documentation site. Switching to "kramdown" which is the markdown engine gh-pages will support after May 1.

modified config to support kramdown markdown rendering

---

_config.yml
auth/index.md
dialogs/index.md
graph/index.md
sample/index.md

Got feedback from GitHub Pages support and found you need an extra space in the '##' headings for the text to render as a heading. Modified all the markdown files to support this syntax so pages should correctly render the headings. Also based off of the page build warning for the pygments highlighter switched to the 'rouge' syntax highlighter in the config.yml file

updated kramdown specific syntax for headings to render

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

fixes integral constant overflow warning in `FacebookSession.cpp` when building the sdk for Windows 10.

force macro to evaluate to long long

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

#104
`WebAuthenticationBroker::AuthenticateAsync` is marked as deprecated for windows phone 8.1, however the behavior of the function changes depending on whether it is a windows 10 or 8.1 phone. Rather than `#ifdef` the call out for windows phone 8.1, the warning is suppressed. Having the function exist in the sdk does not seem to negatively affect the ability of an app to pass Windows App Certification Kit.

suppressed WebAuthenticationBroker::AuthenticateAsync warning

---

samples/LoginCpp-UWP/LoginCpp/Resources.resw
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

#128
WebAccountProvider redirect uri now uses phone SID instead of desktop SID, allowing the login flow to return back to the correct app.

Fix web account provider login flow

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookAccessTokenData.cpp

Makes better use of `Windows::Globalization::Calendar` to calculate the expiration time of the token instead of us doing the math ourselves.

FBAccessTokenData expiration time refactor

---

samples/LoginCpp-UWP/LoginCpp/UserInfo.xaml
samples/LoginCpp-UWP/LoginCpp/UserInfo.xaml.cpp
samples/LoginCpp/LoginCpp/LoginCpp.Shared/UserInfo.Shared.xaml.cpp
samples/LoginCpp/LoginCpp/LoginCpp.Windows/UserInfo.xaml
samples/LoginCs/LoginCs/LoginCs.Shared/UserInfo.xaml.cs
samples/LoginCs/LoginCs/LoginCs.Windows/UserInfo.xaml
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookProfilePictureControl.xaml.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookProfilePictureControl.xaml.h

#58 
`ProfilePictureControl::UserId` is now implemented as a dependency property. Changing its value will update the profile image if successful. If no value is set then a default image will be shown instead of the control remaining blank.

ProfilePictureControl::UserId dependency property

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookPermissions.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookPermissions.h
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

Fix for #169 . `FBSession::LoginAsync` will now also fail to login if the saved access token does not grant all of the permissions that are being requested.

SessionLoginBehavior::Silent login/logout toggling behavior fix

---

samples/LoginCpp-UWP/LoginCpp/LoginCpp.vcxproj
samples/LoginCpp-UWP/LoginCpp/LoginCpp.vcxproj.filters
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookClient.cpp

#156
Expects the user to override the `ToString` method on their custom object to return a valid (probably json) string.

FBClient::SerializeParameters uses ToString() as a backup

---

winsdkfb/winsdkfb_uwp/winsdkfb_uwp/FBAppEvents/FacebookAppEvents.cpp
winsdkfb/winsdkfb_uwp/winsdkfb_uwp/FBAppEvents/FacebookAppEvents.h

Activate is using CurrentApp:: which will crash for any app that is not installed via store (aka not yet published).   With simulator support, folks will get around this and still be able to follow their unit tests that use simulator.   
While doing this I also added a little exception handling to activate as that shall never have unhandled exceptions..   
I did both of these in the 'least intrusive' way... though more refactoring could improve error handling in other places, it seems this is now calling facebook no matter what..   [lmk if you want me to do the latter]

simulator support for FBSDKAppEvents::Activate()  

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

I would like to suggest these two minor changes.
1. Try and save the token data after having set a new token, like in a scenario in which the token gets extended. Either like in this PR by calling TrySaveTokenData in setter, or by changing access level of TrySaveTokenData to public and allow external code to call.
2. Don't instatiate the FacebookDialog too early, we've had some issue on which the app is trying to silently reauthenticate when app is launching, but from a background thread, which causes the instantiation of FacebookDialog to throw exception. Instantiation is already being handled by actual dialog calls.

Minor tweaks based on usage of sdk

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookDialog.xaml

Fixed close button that appears stretched on Windows Phone 8.1.
Other improvements to look better.

Improved FacebookDialog UI for 8.1 projects

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

This minor tweak will remove the exception thrown when trying to find an existing FBSDKData file. Keep earlier behavior for WP8.1 compatibility

Using TryGetItemAsync when Win10

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookSession.cpp

Upon logging in, some basic user data is queried and stored in an `FBUser` object that can be accessed from `FBSession`. One of these fields is metadata about the user's profile picture. This change explicitly queries for the profile picture data in cases where it is no longer provided by default.

add picture to list of fields to query about initial user data

---

winsdkfb/winsdkfb/winsdkfb.Shared/FacebookPaginatedArray.cpp
winsdkfb/winsdkfb/winsdkfb.Shared/FacebookPaginatedArray.h

This adds a field to FbPaginatedArray alongside with 'current', which is the data array. 
My scenario is that we are building a UWP app that needs to talk to a win32 process, they can only talk in strings through "AppServices". Once I have the data from FB, with this we don't have to translate the JsonArray back to String.

Add CurrentDataString to FacebookPaginatedArray
